### PR TITLE
1st round of WebRV layers

### PR DESCRIPTION
**Pull request by shelbysawyer**
#584

### CODE REVIEW

**Comment by shelbysawyer** [comment]
@MattReimer I saw that the commit for the vbet_extent_hollow.json file failed-- I went back and redid it and pushed the new file and it looks like that one failed too. I can't figure out why.

**Review by MattReimer — APPROVED** [review]
These look great on first glance


EDIT: I didn't see the check failures. I'm looking into it.

**Review by MattReimer — CHANGES_REQUESTED** [review]
See my comments about the shape of the JSON above

**Comment by MattReimer** [comment]
I'm really sorry @shelbysawyer. Those docs are a bit outdated and we need to fix that. I'll put in a ticket

There is updated documentation here:

https://github.com/Riverscapes/RiverscapesXML/blob/master/docs/Symbology/webRAVEVectors.md

Also I'm happy to do a call today or if you want to collect a bunch of people I can do a tutorial / workshop on this. I know it's always a good chunk of time between working on this stuff and it's easy to forget how it all works.

**Comment by shelbysawyer** [comment]
Ah, okay. Thanks for linking the updated documentation. 

I'll take you up on that training! @jtgilbert emailed @wally-mac to coordinate with the lab folks to find a time. Thanks @MattReimer!

**Pull request closed without merging**
