### PR TITLE
added rim qml files

### PR DESCRIPTION
**Pull request by Jdgilby**

### CODE REVIEW

**Comment by Jdgilby** [comment]
Valley_Bottom

**Comment by Jdgilby** [comment]
Thalwegs

**Comment by Jdgilby** [comment]
Dam_State

**Comment by Jdgilby** [comment]
Crest_Type

**Comment by Jdgilby** [comment]
Wetted_Extent

**Comment by Jdgilby** [comment]
Max_Min_Inundation

**Review by MattReimer — APPROVED** [review]

**Pull request merged**
