### PR TITLE
Some VBET Business Logic & Symbology Changes

### PR DESCRIPTION
**Pull request by joewheaton**
This was partly me playing around and getting carried away and partly some stuff I needed quickly for some work this week with @philipbaileynar. This will change in future, but @shelbysawyer and I can go back and forth on this. In meantime, this will make VBET projects much easier to make improvements from. Note, I have not updated Arc *.lyr files to take advantage of these updates.

### CODE REVIEW

**Comment by joewheaton** [comment]
@shelbysawyer 

## New Views

### VBET Default View
I made the default view just include the 50% and 100% outlines on top of hillshade:
image

It also works well for aerial imagery (shown here with NAIP and hillshade turned off)
image

### VBET Inputs
I added a new VBET inputs, which just shows the DEM and Hillshade, and the VBET network symbolized by bankfull width
image

-----------

## New VBET Outlines
### Hollow
These probably typically won't be viewed all together, but when they are they look like this:
image
These are helpful for interpreting outputs with relationship to context layers (e.g. aerial photos, DEM, etc.)


### Transparent
This will sometimes be altogether:
image



### Likelihood Map
Categories can change... and we can tweak what I've used... but for now:

image

**Review by MattReimer — APPROVED** [review]
Looks fine to me.

**Comment by joewheaton** [comment]
Hey @MattReimer.... sorry @philipbaileynar told me how seriously you take the reviewers. I just removed @shelbysawyer  (she may not have known about the review) so we can get that merged for tomorrow's meeting. Thanks for how quickly you have turned these around.

**Comment by MattReimer** [comment]
@joewheaton  it is done.

**Comment by shelbysawyer** [comment]
> Hey @MattReimer.... sorry @philipbaileynar told me how seriously you take the reviewers. I just removed @shelbysawyer (she may not have known about the review) so we can get that merged for tomorrow's meeting. Thanks for how quickly you have turned these around.

Oops-- yep, I read through this but didn't realize I was a reviewer. I'll get used to looking for that. Thanks!

**Comment by joewheaton** [comment]
Not to worry @shelbysawyer... there will be plenty more ;)
_____________________
Dr. Joseph M. Wheaton
435-554-1247 (direct) | http://www.joewheaton.org

**Pull request merged**
