### PR TITLE
Qrave brat curation

### PR DESCRIPTION
**Pull request by Cashe93**
These changes are tracked in issue #145. All of BRAT QML files have been authored and most have been tested, except for the riparian vegetation (see #164). There were also a couple of changes made to the business logic:

- added 'watts' label to the hydrology node names as a test to see if this is what we want to do for the entire tree?
- added a couple of project views

### CODE REVIEW

**Review by joewheaton — APPROVED** [review]
Lets get this merged in and have a look how it works. Nice work.

**Comment by Cashe93** [comment]
Sounds good @joewheaton. Do I need to do anything further to get this merged?

**Comment by joewheaton** [comment]
> Sounds good @joewheaton. Do I need to do anything further to get this merged?

Looks like problem is the Pull Request was assigned to you and not @MattReimer.

**Comment by MattReimer** [comment]
This looks good. I'm merging it.

**Comment by Cashe93** [comment]
@joewheaton, when you get a chance, let me know what you think about the BRAT QRAVE projects. I've just looked it over and it seems like we are mostly there. I found a couple of missing layers which have since been created and will be part of the next pull request. The biggest issue is with the categorical rasters not symbolizing correctly which is being discussed in #164

**Comment by joewheaton** [comment]
> @joewheaton, when you get a chance, let me know what you think about the BRAT QRAVE projects. I've just looked it over and it seems like we are mostly there. I found a couple of missing layers which have since been created and will be part of the next pull request. The biggest issue is with the categorical rasters not symbolizing correctly which is being discussed in #164

Will do @Cashe93. See #203 to solicit others eyes too. Great job on this.

**Pull request merged**
