### PR TITLE
Updated Land Use symbology for pyBRAT

### PR DESCRIPTION
**Pull request by Cashe93**
Based on #395. 

Note: This same fix will need to be done for Vegetation suitability rasters.

### CODE REVIEW

**Comment by MattReimer** [comment]
@Cashe93 did you check that these work for QRave?

**Comment by Cashe93** [comment]
@MattReimer, yes it works in Q.

**Comment by jtgilbert** [comment]
@Cashe93 Looking at this I noticed that the labels were different before. I just pulled the "very low" "low" etc. from the symbology for land use applied to the network. Do you know if Joe prefers to have the raster symbolized with those labels that indicated land use type?

**Comment by Cashe93** [comment]
I'm away from my computer, but I'm pretty sure its the same. You can confirm this by opening the py_lu.lyr from the pyBRAT esri symbology folder. That's what we want to be basing the Q and web  symbology on.

**Comment by jtgilbert** [comment]
@Cashe93 Yeah here's current legend. Do you want to go back and edit the files or do you want to scrap the branch and have me redo it?

**Comment by Cashe93** [comment]
If it's not too much work,  I say we scrap it and redo it.  If it's less work to edit, i can do that also.

**Pull request closed without merging**
