### PR TITLE
VBET IGO at Zoom 

### PR DESCRIPTION
**Pull request by Cashe93**
Testing adding IGO zoom symbology to .json

### CODE REVIEW

**Review by MattReimer — APPROVED** [review]

**Comment by Cashe93** [comment]
@MattReimer it doesn't look like this worked. Are there any glaring mistakes that you can see within the [.json](Symbology/web/VBET/igo_est_prop_vb_channel.json)?

**Comment by Cashe93** [comment]
@MattReimer, has this been merged with the master branch yet?

**Review by MattReimer — APPROVED** [review]

**Comment by MattReimer** [comment]
Just did it. Sorry this fell into the cracks.

**Comment by Cashe93** [comment]
No problem. It looks like this worked! I'll work on getting this applied to the rest of the VBET IGOs.

**Pull request merged**
