### PR TITLE
Demoing adding the DEM symbology

### PR DESCRIPTION
**Pull request by joewheaton**
Hi M@. This is us getting started on some branches and pull requests for QMLs.

### CODE REVIEW

**Comment by joewheaton** [comment]
This was based on applying the DEM symbology used in ArcRAVE [dem.lyr](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/esri/Shared/dem.lyr) to a new *.qml format. It looks like this:
image

**Review by shelbysawyer — APPROVED** [review]

**Review by lauren-herbine — APPROVED** [review]
Looks fantastic

**Comment by shelbysawyer** [comment]
@lauren-herbine

**Comment by MattReimer** [comment]
Looks fine to me. I can't figure out how to do stretched colour ramps for QGIS but we'll get there. Once I approve and merge you should be able to click the "Update Resources" menu item in QRAVE and get the updated qml file.

**Pull request merged**
