### PR TITLE
creating symbology for confinement ratio

### PR DESCRIPTION
**Pull request by lauren-herbine**
first confinement project symbology

### CODE REVIEW

**Comment by lauren-herbine** [comment]
image

**Review by MattReimer — CHANGES_REQUESTED** [review]
hey @lauren-herbine,

case matters with the filenames so can we make them all lowercase for the qml files?

Symbology/qgis/Confinement/confinement_margins.qml
Symbology/qgis/Confinement/confinement_ratio.qml

**Comment by lauren-herbine** [comment]
@MattReimer yes- for sure

**Comment by lauren-herbine** [comment]
@MattReimer I keep on trying to change it but for some reason the change isn't showing up?

**Comment by lauren-herbine** [comment]
See question #101

**Review by MattReimer — APPROVED** [review]
Looks good now. I'm going to merge this

**Pull request merged**
