### PR TITLE
Most of ChannelArea for WebRave

### PR DESCRIPTION
**Pull request by lauren-herbine**
This is ChannelArea for WebRave. Wooo! #166

### CODE REVIEW

**Comment by lauren-herbine** [comment]
Hi @MattReimer and @joewheaton - I am realizing that for reviewers to be able to review a WebRave project, the pull request would already have to go through... In fact, I can't even really see what my end product looks like until we complete the pull request and then I look at it on the staging server (right??). I put @joewheaton and @shelbysawyer on here as reviewers, but now I am worried that that will hold up the pull request, as they don't actually have anything to look at.

**Comment by MattReimer** [comment]
@lauren-herbine yes this is all true. I think for webrave it's probably just best for me to be a reviewer for now. 

Once webrave is formally launched we'll have a staging server we can use for testing again and that should help somewhat

**Comment by lauren-herbine** [comment]
Ok, great, I'll take @joewheaton and @shelbysawyer off!

**Comment by MattReimer** [comment]
All your files look good to the eye. I'm going to merge this quickly so we can see it in the wild

**Comment by joewheaton** [comment]
@MattReimer can you provide link to the staging server that you "reviewed" these at so we can have a peak?

**Comment by lauren-herbine** [comment]
@joewheaton @MattReimer it actually looks like most of it isn't working in WebRAVE. I know you said the code looked alright, Matt, but perhaps we can discuss at the workshop today? All of the inputs came in correctly (symbolized correctly and everything), but intermediates and outputs did not. [Here](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/61d63732-c0d8-4ac8-b5d4-3f27dc855609) is a project. And here is a screenshot showing the tile errors:
image

**Comment by MattReimer** [comment]
Oh, ok. @lauren-herbine Tiling errors have nothing to do with symbology so you're probably still good. I'll explain in the call

**Comment by lauren-herbine** [comment]
Ok, thanks @MattReimer !

**Comment by MattReimer** [comment]
Just so you know we're tracking this:
https://github.com/Riverscapes/rs-web-monorepo/issues/132

**Pull request merged**
