### PR TITLE
EVT and BPS Vegetation Rasters Symbolized for QRave & WebRAVE

### PR DESCRIPTION
**Pull request by MattReimer**
@Cashe93 I'm done here. This is related to #265 

I popped it open in QGis and everything seemed right but I'm going to lean on you to make sure everything is working as expected.

Things to check:

1. [x] Two new symbologies have been added for Riparian. they are called `Existing_Veg_EVT_Riparian` and `Historic_Veg_BPS_Riparian`. The business logic has also been updated with the new Riparian/non-riparian layers. Make sure they work and make sure you like the naming, order etc.
2. [x] New QML files have been added for QRave. Legend labeling is about as good as we can get but feel free to make suggestions
3. [ ] WebRAVE CSVs have been added

If you're curious about the code to do this it is here:

https://github.com/Riverscapes/RiverscapesXML/blob/evtbps/python/jupyter/veg_rasters/evt_bps.ipynb

@Cashe93 Please do as thorough a review as you can and then I'll merge this.

### CODE REVIEW

**Comment by MattReimer** [comment]
I needed to update my python tests to account for weird label names and an alpha column. Should be working now.

**Comment by Cashe93** [comment]
@MattReimer, I'm having a hard time seeing the changes.  To test these do I just need to switch to the evtbps branch and fetch origin? Then all of the changes should be visible?

**Comment by MattReimer** [comment]
You need to pull on that branch and then copy the qml files and the business logic to the right place beside the project you're testing (kind of like you would for any other project)

**Comment by Cashe93** [comment]
@MattReimer, most of this looks great. Three things to point out (which you likely already know).

1. I noticed that there is a discrepancy in BPS name between Q and Arc. Notice the White space in Q, where in Arc its a purple color. 

image

2. A small comment on the riparian rasters; the RGB values in Q are 0,255,0 which seems a bit bright. I think the RGB values should be 56,168,0. Other than that, its displaying properly. 

QRAVE
image

ArcRAVE
image


3. The EVT Class legend is quite confusing. There are multiple colors for the same category, some are labeled with the VALUE and not the actual category, etc. I'm not sure if this can be fixed but just thought I'd point it out.  

image

**Comment by MattReimer** [comment]
@cashe93 try it now

1. I suspect that if you're looking at brat you might be seeing a QML in the BRAT folder that is overriding the one in the shared folder. I have deleted the redundant one in the BRAT folder so hopefully that will be better
2. The greens should be the right shade (easy fix)
3. There was a bug in the EVT Class export script (nice catch BTW. THis is why we test!)

Problem (1) might be harder to solve but take a look at tell me if we're closer.

**Comment by Cashe93** [comment]
@MattReimer, the riparian colors look much better, and the EVT Class legend is looking a lot better as well. However, the same issue still exists with for the BPS Name raster.

**Comment by MattReimer** [comment]
Glad to hear it. I'm all out of time to work on this today. Do you think you could do a little investigating as to what that purple color is? Everything else seems fine so I'm suspicious. 

Maybe see if you can figure out what that raster value is and then see whether QGIS has an entry for it. There must be a reason it's not showing. 

Also it would be helpful to tell me what dataset you're looking at so I can try to reproduce it. 

I'll likely have a little time later in the week to open this back up again.

**Review by Cashe93 — APPROVED** [review]
@MattReimer, as discussed this is most of the way there. We can update this later once we find out the specific cause for BPS discrepancies.

**Pull request merged**
