### PR TITLE
Veg conv raster

### PR DESCRIPTION
**Pull request by dominique-shore**
Adding vegetation conversion for web and qrave.

### CODE REVIEW

**Review by jtgilbert — COMMENTED** [review]
@dominique-shore looks like in the qml conversion is capitalized and in the .txt it's lower-case. They need to be the same, and match what is in the business logic (which it looks like you changed to lower case?)

**Comment by dominique-shore** [comment]
> @dominique-shore looks like in the qml conversion is capitalized and in the .txt it's lower-case. They need to be the same, and match what is in the business logic (which it looks like you changed to lower case?)

Okay - that's kind of interesting. I noticed the differences in spelling after I'd added the .txt folder, so I changed the file name locally to `Veg_conversion_raster.txt` to match business logic, but GitKraken didn't pick that up as a committable change. I'll just cut the file from the web folder and then paste it back in. That should solve the problem?

**Comment by dominique-shore** [comment]
> @jtgilbert Okay - that's kind of interesting. I noticed the differences in spelling after I'd added the .txt folder, so I changed the file name locally to `Veg_conversion_raster.txt` to match business logic, but GitKraken didn't pick that up as a committable change. I'll just cut the file from the web folder and then paste it back in. That should solve the problem?

I cut it out and then back in, and it's still not showing up as something that I can commit on GitKraken. On my desktop, the .qml and .txt files are named `Veg_conversion_raster` with that capitalization, to match business logic, so I'm not sure how to change the spelling on GitHub.

**Comment by dominique-shore** [comment]
> @dominique-shore looks like in the qml conversion is capitalized and in the .txt it's lower-case. They need to be the same, and match what is in the business logic (which it looks like you changed to lower case?)

@jtgilbert I changed Veg_Conversion_raster.qml to Veg_conversion_raster.qml

**Review by jtgilbert — APPROVED** [review]

**Pull request merged**
