### PR TITLE
QRAVE Compliance - Riverscapes Context

### PR DESCRIPTION
**Pull request by Tanmanfalcon**
Project Type: RS Context
Layer(s): All folders
Type(s) - Raster & Vector

Description
-Got RS Context to be QRAVE compliant by authoring .qml and updating business logic as needed.
-Added all symbology in QRAVE to mimic ArcRAVE. 
-Changed the name of Bankfull flowlines to Estimated Bankfull Width. 
-Modified a few preexisting QMLs to more closely match ArcRAVE
-Changed Vegetation folder to LANDFIRE and added Vegetation as a subfolder, with existing and historic vegetation inside. 
-Modified the order of the Vegetation folder structure to be less repetitive.
See Issue #148 for screenshots of the outputs.

### CODE REVIEW

**Review by joewheaton — APPROVED** [review]
This is a huge one @Tanmanfalcon. Nice work. As best I can tell from these and #148 this looks good. I'm looking forward to having Riverscapes Context working great in QRAVE.

**Review by joewheaton — APPROVED** [review]

**Comment by joewheaton** [comment]
Hey @Tanmanfalcon and @Cashe93. I noticed your pull requests were assigned to yourselves. Make sure to assign them to @MattReimer in future. All the issues for which you have all your commits are typically assigned to yourselves. But on RiverscapesXML, when you make a pull request, assign it to @MattReimer so it actually shows up in his queue. Nice job.

**Comment by MattReimer** [comment]
Hmm. We have a little problem @Tanmanfalcon. Looks as if the[ BRAT Curation pull](https://github.com/Riverscapes/RiverscapesXML/pull/193) by @Cashe93 request conflicts with this one on a number of qml files. 

Here are the files that differ:

* Symbology/qgis/Shared/flow_lines.qml
* Symbology/qgis/Shared/Existing_Veg_EVT_Class.qml
* Symbology/qgis/Shared/Existing_Veg_EVT_Name.qml
* Symbology/qgis/Shared/Historic_Veg_BPS_Name.qml

I'm not suggesting we try to resolve conflicts in QML files since that's WAY too messy but we should probably choose someone as the winner and just use their files.

@Cashe93 and @Tanmanfalcon could you both have a lively discussion and figure out whose qml files I shoud use and let me know?  @Cashe93 your files are now merged to `master` since that's the PR I merged first. @Tanmanfalcon yours are still on the `QRave_RiverscapesContext_Curation`

**Comment by Cashe93** [comment]
@MattReimer thanks for catching that. We will compare those QMLs and let you know which ones to use.

**Comment by Tanmanfalcon** [comment]
@MattReimer @Cashe93 Go ahead and use the qml's that Cashe created. Since we both created the qml's using SLYR, they should be the same

**Pull request merged**
